[package]
name = "colorful-light2d"
version = "0.1.0"
authors = ["董哒哒 <dongyu_1991@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.8"
rand = "0.8.0"